# Generated by Django 3.0.5 on 2020-07-22 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentic', '0003_fullform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fullform',
        ),
    ]
