# Generated by Django 3.0.5 on 2020-07-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentic', '0005_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='important',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
